### ISSUE TITLE
Publish on crates.io for easy installation

### ISSUE THREAD

**Issue by kellenff** [acidnik/ppcp#2]
It'd be great to be able to do `cargo install ppcp`, thanks!

**Comment by acidnik** [comment]
As soon as my pr https://github.com/mitsuhiko/indicatif/pull/91 is landed, I will remove the custom dependency from Cargo.toml and publish. For now cargo does not allow to publish crate with dependencies sourced from a repository

**Comment by kiedtl** [comment]
Or better yet, create a HomeBrew/AUR/[Scoop](https://scoop.sh) package for easy installation for those who don't have Rust installed.

**Comment by dsully** [comment]
Looks like the indicatif PR has been merged..

**Comment by acidnik** [comment]
Ask, and you shall receive
https://crates.io/crates/ppcp
Sorry for the delay
